### ISSUE TITLE
Diceware as a service

### ISSUE THREAD

**Issue by LSJim** [biddster/diceware#1]
Can we have this as a service - I can't be bothered to install it locally...

**Comment by biddster** [comment]
Lots of those around:

https://diceware.herokuapp.com/
https://entima.net/diceware/
http://rumkin.com/tools/password/diceware.php
http://www.zanfar.com/diceware/index.php

**Comment by LSJim** [comment]
Not my point. ;-)—

**Comment by biddster** [comment]
Then I'm not with you...

**Comment by LSJim** [comment]
I don't trust anyone else.  And I thought you'd knock together a node service for fun.  Anyway, I was pulling your leg. —

**Comment by biddster** [comment]
Oh I see...I was just thinking that they all use similar cryptographic methods to select from the same wordlist.

It can be run as an applet, and it is a runnable jar so it's not too onerous.

**Comment by LSJim** [comment]
Sure. I've run it before. Nice. —

**Comment by biddster** [comment]
1password wins.
